### PR TITLE
xClusterProperty: Add BlockCacheSize property -- Fix for issue #252

### LINKED ISSUE #252: xClusterProperty: add support for BlockCacheSize for CSV Volume Cache
#### Details of the scenario you tried and the problem that is occurring
xClusterProperty does not support the BlockCacheSize property which enables Cluster Shared Volume Caching.

#### Suggested solution to the issue
Add BlockCacheSize to the supported properties list that xClusterProperty can test and set.

#### The operating system the target node is running
Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 all have the ability to enable a CSV Volume Cache through the BlockCacheSize cluster property

#### Version of the DSC module that was used
1.15.0

### PR DESCRIPTION
**Pull request by jambar42**
#### Pull Request (PR) description
Added BlockCacheSize property to xClusterProperty

#### This Pull Request (PR) fixes the following issues
- Fixes #252

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/253)

### CODE REVIEW

**Comment by jambar42** [comment]
tagging @johlju directly

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/253)* status: all files reviewed, 4 unresolved discussions (waiting on @jambar42)

*[a discussion](https://reviewable.io/reviews/dsccommunity/xfailovercluster/253#-MVCcp087RXrZsHBM104:-MVCcp087RXrZsHBM105:bq879e6) (no related file):*
I like to see a unit test that covers this change, at least for Get and Test. Set looks like difficult to mock as it is currently implemented so I'm okay with you skipping test for Set. :slightly_smiling_face: 

---
___
*[CHANGELOG.md, line 9 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/253#-MVCb_HO8sIcQg2qlyqF:-MVCb_HO8sIcQg2qlyqG:bxwqeeo) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/ee05cc1fef4078b212e64600ad2df75e290f77fd/CHANGELOG.md#L9)):*
> ```
> xFailoverCluster
> ```

We can change this to 'xClusterProperty' so any other changes are grouped together.
___
*[CHANGELOG.md, line 9 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/253#-MVCbnZ0EibOHBP3o8uQ:-MVCbnZ0EibOHBP3o8uR:bajizpb) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/ee05cc1fef4078b212e64600ad2df75e290f77fd/CHANGELOG.md#L9)):*
> ```Markdown
> 
> ## [Unreleased]
> - xFailoverCluster
> ```

Please add the these under a section '### Added' (as per "Keep a change log").
___
*[CHANGELOG.md, line 10 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/253#-MVCbPes-C72Fa6-uapU:-MVCbPes-C72Fa6-uapV:b8kejlx) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/ee05cc1fef4078b212e64600ad2df75e290f77fd/CHANGELOG.md#L10)):*
> ```
> Added the BlockCacheSize parameter to xClusterProperty.
> ```

Please add a reference to the issue that will be resolved.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/253#-:-MW0fm6u48MyCoZMy6ja:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jambar42)

**Comment by johlju** [comment]
@jambar42 great work on this, thank you! 🙂

**Pull request merged**
