### PR TITLE
xFailOverCluster: Changed unit tests to handle missing DscResource.Test better

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description
- xFailOverCluster
  - Changed unit tests to handle missing DscResource.Test better.

#### This Pull Request (PR) fixes the following issues
None

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/217)

### CODE REVIEW

**Comment by wsmelton** [comment]
@johlju @gaelcolas Looks good to me (at least what I understand of the testing process).

**Comment by gaelcolas** [comment]
Updating changelog with #218 and will rebase after. That should clear the conflict, if not will fix manually.

**Comment by gaelcolas** [comment]
@johlju can you check the changelog? I've fixed & merged the PR for changelog, I think this needs merging "both", but you know better than I do.

**Comment by johlju** [comment]
Yep, I resolved the conflicts. Will merge as soon as the tests passes.

**Comment by johlju** [comment]
@wsmelton thank you for the review! 😄

**Pull request merged**
