### PR TITLE
xCluster: Make DomainAdministratorCredential optional

### LINKED ISSUE #70: xCluster: DomainAdministratorCredential should not be mandatory
**Details of the scenario you tried and the problem that is occurring:**
It should be possible to use built-in parameter `PsDscRunAsCredential` for WMF 5.x, so the parameter `DomainAdministratorCredential` should not be mandatory. 

**The DSC configuration that is using the resource (as detailed as possible):**
```powershell
xCluster "Create$($Node.FailoverClusterName)"
{
    Name = $Node.FailoverClusterName
    StaticIPAddress = $Node.FailoverClusterIPAddress

    PsDscRunAsCredential = $SqlInstallCredential
}
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
n/a

### LINKED ISSUE #164: xCluster: Must provide DomainAdministratorCredential
I ran into an issue when utilizing this resource where I didn't want to provide a DA credential. In my environment, we utilize machine identities to ACL most of our resources so we can avoid using passwords in 99.9% of situations. Unfortunately, this resource doesn't support this.
Suggested fixes:

Changed the "DomainAdministratorCredential" property in the schema to "write" (was required).
Changed the "DomainAdministratorCredential" parameter in the resource to "Mandatory = $false".
Wrapped the Set-ImpersonateAs function in an if statement to check for the "DomainAdministratorCredential" key exists in $PSBoundParameters.

### PR DESCRIPTION
**Pull request by jrdbarnes**
#### Pull Request (PR) description

This PR makes the DomainAdministratorCredential parameter optional for xCluster. 
In order to fulfill the use-case where Cluster Name Objects are prestaged in Active Directory 
prior to cluster creation as per [microsoft docs](https://docs.microsoft.com/en-us/windows-server/failover-clustering/prestage-cluster-adds). 

#### This Pull Request (PR) fixes the following issues

- Fixes  #164 
- Fixes #70 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
Thank you 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-:-MRFQB-t-a2hMoKjJb9I:b-9755fo)* status: all files reviewed, 4 unresolved discussions (waiting on @jrdbarnes)

*[a discussion](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-MRFQc4o2bWU4OkyHF8a:-MRFQc4o2bWU4OkyHF8b:b-fei7yc) (no related file):*
Please add a unit test that verifies that when called without parameter `DomainAdministratorCredential` the function `Set-ImpersonateAs` is not called. For all three functions Get-, Test-, and Set-TargetResource. 'https://github.com/dsccommunity/xFailOverCluster/blob/main/tests/Unit/MSFT_xCluster.Tests.ps1

---
___
*[README.md, line 70 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-MRFP5zVEot6ZShTxsOx:-MRFP5zVEot6ZShTxsOy:bjg586h) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/649e59286dea46639ef2c5be9ddd2e9e5ac0608d/README.md#L70)):*
> ```
>   create the failover cluster in Active Directory. If this is not specified then
>   the cluster computer object should have been prestaged as per the
> ```

Curious. Must the configuration be run with `PsDscRunAsCredential` when leaving out  `DomainAdministratorCredential`, or should it be run with SYSTEM? If so maybe we can mention that as well  that the credential in `PsDscRunAsCredential` must have permission to the prestaged cluster computer object? What permissions are needed, is that known?
___
*[source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 60 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-MRFOVTuAvmDTc3_EOKM:-MRFOVTuAvmDTc3_EOKN:b-fzyjxz) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/649e59286dea46639ef2c5be9ddd2e9e5ac0608d/source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L60)):*
> ```PowerShell
>     }
> 
>     try
> ```

Can we add `context = $null` prior to the `try`-block to make it more visible what will happen in the `finally`-block?  :slightly_smiling_face: 
___
*[source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 95 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-MRFNvQp-Ctq_97CCBqo:-MRFNvQq459r9EB01AZz:b-m3uuqy) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/649e59286dea46639ef2c5be9ddd2e9e5ac0608d/source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L95)):*
> ```
> $returnvalue.Add('DomainAdministratorCredential'
> ```

We should always return all properties, if `DomainAdministratorCredential` is not set then we should return $null.

In this case we can keep `DomainAdministratorCredential = $DomainAdministratorCredential` which will set it to $null if the parameter was not set by a configuration.

**Comment by johlju** [comment]
@jrdbarnes great work on this! Just tiny comments, and please add unit tests for this change. 🙂

**Review by jrdbarnes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @johlju and @jrdbarnes)

___
*[README.md, line 70 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-MRFP5zVEot6ZShTxsOx:-MRdk_9t0kmCkcdKl3kg:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/649e59286dea46639ef2c5be9ddd2e9e5ac0608d/README.md#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>   create the failover cluster in Active Directory. If this is not specified then
>   the cluster computer object should have been prestaged as per the
> ```

Curious. Must the configuration be run with `PsDscRunAsCredential` when leaving out  `DomainAdministratorCredential`, or should it be run with SYSTEM? If so maybe we can mention that as well  that the credential in `PsDscRunAsCredential` must have permission to the prestaged cluster computer object? What permissions are needed, is that known?
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 60 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-MRFOVTuAvmDTc3_EOKM:-MRdkdTJ70FNwe1Hd3oY:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/649e59286dea46639ef2c5be9ddd2e9e5ac0608d/source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L60)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we add `context = $null` prior to the `try`-block to make it more visible what will happen in the `finally`-block?  :slightly_smiling_face: 
</blockquote></details>

Done.
___
*[source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1, line 95 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-MRFNvQp-Ctq_97CCBqo:-MRdkee090dc1xKS1c5I:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/649e59286dea46639ef2c5be9ddd2e9e5ac0608d/source/DSCResources/MSFT_xCluster/MSFT_xCluster.psm1#L95)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $returnvalue.Add('DomainAdministratorCredential'
> ```

We should always return all properties, if `DomainAdministratorCredential` is not set then we should return $null.

In this case we can keep `DomainAdministratorCredential = $DomainAdministratorCredential` which will set it to $null if the parameter was not set by a configuration.
</blockquote></details>

Done.

**Review by johlju — CHANGES_REQUESTED** [review]
Looks good, just missing a unit test as mentioned in the previous comment.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-:-MRfiaFq-fdHnehISG2J:b-m66ofe)* status: all files reviewed, 1 unresolved discussion (waiting on @jrdbarnes)

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-:-MTukzbV53zbF44Wm0iD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
@jrdbarnes thank you for this! Great work! 😃  Will merge and release once the test passes.

**Comment by jrdbarnes** [comment]
Hi @johlju, I was trying to add more tests for Set and Test, and then going to rebase before merge, what do you think?

**Comment by johlju** [comment]
Sure. I always want more tests. 😄  Let me know when you are ready.

**Comment by jrdbarnes** [comment]
First time with Pester, so slow going 😄

**Comment by johlju** [comment]
No worries. 😃 Take your time. 😊

**Comment by jrdbarnes** [comment]
I'm ready for merge when ever you are happy with that @johlju

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/249#-:-MTvNs9EBjtOtYg613nJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrdbarnes)

**Comment by johlju** [comment]
@jrdbarnes looks good to me!

**Pull request merged**
