### PR TITLE
BREAKING CHANGE: xFailOverCluster renamed to FailoverClusterDsc: Renamed all DSCResources, Examples, Modules and Tests where applicable

### LINKED ISSUE #69: xFailOverCluster: Rename when this module is becoming HQRM
**Details of the scenario you tried and the problem that is occurring:**
This might be getting ahead of things. But, when we get to the point that this module is HQRM and being renamed from experimental naming, I suggest we name it FailoverClustersDsc to match the Failover Clustering PowerShell module.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by nickgw**
#### Pull Request (PR) description
Rename module to FailoverClusterDsc from xFailOverCluster

#### This Pull Request (PR) fixes the following issues
- Fixes #69 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/failoverclusterdsc/264)

### CODE REVIEW

**Comment by johlju** [comment]
@nickgw  can you send in anther PR deprecating the previous module? Just change the CHANGELOG.md under the Unreleased section:

   ```
   ### Deprecated

   **The module _xFailOverCluster_ will be renamed _FailoverClusterDsc_ ([issue #69](https://github.com/dsccommunity/xFailOverCluster/issues/69)).
   The version `v1.6.1` will be the the last release of _xFailOverCluster_.
   The Version `v2.0.0` will be release as _FailoverClusterDsc_, it will be
   released shortly after the `v1.6.1` release to easily transition to the
   new module.** The prefix 'x' will be removed from all resources in
   _FailoverClusterDsc_.
   ```

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 54 of 54 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264)* status: all files reviewed, 10 unresolved discussions (waiting on @nickgw)

___
*[`CHANGELOG.md` line 9 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p5Z5c8X-fV-9BzdiE:-N2p5Z5c8X-fV-9BzdiF:b-i83ck6) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L9)):*
> ```Markdown
> 
> ## [Unreleased]
> - BREAKING CHANGE
> ```

Before this we should add section  `### Changed`.



_Code quote:_
```Markdown
- BREAKING CHANGE
```
___
*[`CHANGELOG.md` line 24 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p5ecEBr2wI9NfPvze:-N2p5ecEBr2wI9NfPvzf:bidljug) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L24)):*
> ```Markdown
> ### Changed
> 
> - FailOverClusterDsc
> ```

Let's keep this xFailOverCluster so it matches what is previously released.



_Code quote:_
```Markdown
FailOverClusterDsc
```
___
*[`CHANGELOG.md` line 31 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7RUU-TmfTejFDixs:-N2p7RUU-TmfTejFDixt:bidljug) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L31)):*
> ```Markdown
> ### Added
> 
> - FailOverClusterDsc
> ```

Let's keep this xFailOverCluster so it matches what is previously released.



_Code quote:_
```Markdown
FailOverClusterDsc
```
___
*[`CHANGELOG.md` line 46 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7TTa2e3Fpli_oJDM:-N2p7TTa2e3Fpli_oJDN:bidljug) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L46)):*
> ```Markdown
> ### Changed
> 
> - FailOverClusterDsc
> ```

Let's keep this xFailOverCluster so it matches what is previously released.



_Code quote:_
```Markdown
FailOverClusterDsc
```
___
*[`CHANGELOG.md` line 72 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7VCK3ZqOBu5IJOz3:-N2p7VCK3ZqOBu5IJOz4:bidljug) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L72)):*
> ```Markdown
> ### Fixed
> 
> - FailOverClusterDsc
> ```

Let's keep this xFailOverCluster so it matches what is previously released.



_Code quote:_
```Markdown
FailOverClusterDsc
```
___
*[`CHANGELOG.md` line 120 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7XcMBDybw68kWQ7h:-N2p7XcMBDybw68kWQ7i:bidljug) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L120)):*
> ```Markdown
> ### Changed
> 
> - FailOverClusterDsc
> ```

Let's keep this xFailOverCluster so it matches what is previously released.



_Code quote:_
```Markdown
FailOverClusterDsc
```
___
*[`CHANGELOG.md` line 135 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7Z-S6gnKM_GpsV6P:-N2p7Z-S6gnKM_GpsV6Q:bidljug) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L135)):*
> ```Markdown
> ### Added
> 
> - FailOverClusterDsc
> ```

Let's keep this xFailOverCluster so it matches what is previously released.



_Code quote:_
```Markdown
FailOverClusterDsc
```
___
*[`CHANGELOG.md` line 140 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7_E1Ez1U5UzLOdW7:-N2p7_E1Ez1U5UzLOdW8:bidljug) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L140)):*
> ```Markdown
> ### Changed
> 
> - FailOverClusterDsc
> ```

Let's keep this xFailOverCluster so it matches what is previously released.



_Code quote:_
```Markdown
FailOverClusterDsc
```
___
*[`source/build.psd1` line 1 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2ph6Iq7dUx8YYUhY9m:-N2ph6Iq7dUx8YYUhY9n:byl07kw) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/f4c289ae2e09d49c0a69bb081ab55f27c3cdd69e/source/build.psd1#L1)):*
> ```PowerShell
> @{
> ```

We can remove this file. It is no longer needed with latest version of ModuleBuilder.
___
*[`source/FailoverClusterDsc.psd1` line 33 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2phsZL8awFqHHZcJdZ:-N2phsZL8awFqHHZcJd_:b-kldnwd) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/source/FailoverClusterDsc.psd1#L33)):*
> ```PowerShell
>         'ClusterDisk'
>         'ClusterNetwork'
>         'ClusterPreferredOwner'
> ```

We can change this to the following because it is now updated when building the module in the pipeline.



_Suggestion:_
```PowerShell
    DscResourcesToExport = @()
```

**Comment by johlju** [comment]
> @nickgw can you send in anther PR deprecating the previous module? Just change the CHANGELOG.md under the Unreleased section:
> 
> ```
> ### Deprecated
> 
> **The module _xFailOverCluster_ will be renamed _FailoverClusterDsc_ ([issue #69](https://github.com/dsccommunity/xFailOverCluster/issues/69)).
> The version `v1.6.1` will be the the last release of _xFailOverCluster_.
> The Version `v2.0.0` will be release as _FailoverClusterDsc_, it will be
> released shortly after the `v1.6.1` release to easily transition to the
> new module.** The prefix 'x' will be removed from all resources in
> _FailoverClusterDsc_.
> ```
> 
> I will then push a last release of xFailOverCluster before we merge this PR.

I can fix this myself now, got a few minutes over.

**Review by nickgw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264)* status: all files reviewed, 10 unresolved discussions (waiting on @johlju)

___
*[`CHANGELOG.md` line 9 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p5Z5c8X-fV-9BzdiE:-N2quEwAAJTjMEUBZezV:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Before this we should add section  `### Changed`.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 24 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p5ecEBr2wI9NfPvze:-N2quFm_0ao9jQOxUyw1:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L24)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's keep this xFailOverCluster so it matches what is previously released.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 31 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7RUU-TmfTejFDixs:-N2quG0l0zSn45E-ONGO:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L31)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's keep this xFailOverCluster so it matches what is previously released.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 46 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7TTa2e3Fpli_oJDM:-N2quGZm-qWtxZRPS7mv:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L46)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's keep this xFailOverCluster so it matches what is previously released.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 72 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7VCK3ZqOBu5IJOz3:-N2quH0V6IWi5oUJV8iY:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's keep this xFailOverCluster so it matches what is previously released.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 120 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7XcMBDybw68kWQ7h:-N2quHDnC0rGwhv_FTzK:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L120)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's keep this xFailOverCluster so it matches what is previously released.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 135 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7Z-S6gnKM_GpsV6P:-N2quHtNC5dY6NuEbvQt:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L135)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's keep this xFailOverCluster so it matches what is previously released.
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 140 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2p7_E1Ez1U5UzLOdW7:-N2quIOm84QZpFAEJSdk:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/CHANGELOG.md#L140)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Let's keep this xFailOverCluster so it matches what is previously released.
</blockquote></details>

Done.
___
*[`source/build.psd1` line 1 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2ph6Iq7dUx8YYUhY9m:-N2quJFN93F76yoaMnzy:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/f4c289ae2e09d49c0a69bb081ab55f27c3cdd69e/source/build.psd1#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this file. It is no longer needed with latest version of ModuleBuilder.
</blockquote></details>

Done.
___
*[`source/FailoverClusterDsc.psd1` line 33 at r1](https://reviewable.io/reviews/dsccommunity/xfailovercluster/264#-N2phsZL8awFqHHZcJdZ:-N2quJx3DfUXzisoFDZT:b-896fix) ([raw file](https://github.com/dsccommunity/xfailovercluster/blob/a809872c328d8ea3c161636da1e14f7581f877b2/source/FailoverClusterDsc.psd1#L33)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can change this to the following because it is now updated when building the module in the pipeline.
</blockquote></details>

Done.

**Comment by johlju** [comment]
@nickgw  awesome work on this, thank you!

**Comment by johlju** [comment]
This is ready for merge as soon as PR #265 has been merged and a full release has been made for xFailOverCluster. After that, before merge, we need to 
- rename the pipeline to the correct name
- rename the GitHub repo
- update branch rules (status checks) in GitHub
- ...possible other things I can see now. 🙂

**Comment by johlju** [comment]
So everything should be prepared behind the scenes so we can merge this. I will do that later today.

**Pull request merged**
